object_type: global_settings
overrides:
  aggregates.create.allowExactDistinctCountMeasures.enabled: 'true'
  aggregates.prediction.checkForNonAdditiveMeasuresAndConstraints.enabled: 'false'
  aggregates.withDistinctCounts.widening.enabled: 'true'
  connection.pool.idleConnectionDuration: 6 hours
  connection.pool.user.idleConnectionDuration: 6 hours
  xmla.auth.token.enabled: 'false'
  xmla.discover.properties.daxdialect: tabular1600
